### 회원가입
POST {{commerce-api}}/api/v1/auth/signup
Content-Type: application/json

{
  "loginId": "{{loginId}}",
  "password": "{{loginPw}}",
  "name": "홍길동",
  "birthDate": "1990-01-15",
  "email": "test@example.com"
}

### 비밀번호 변경
PUT {{commerce-api}}/api/v1/auth/password
Content-Type: application/json
X-Loopers-LoginId: {{loginId}}
X-Loopers-LoginPw: {{loginPw}}

{
  "currentPassword": "{{loginPw}}",
  "newPassword": "NewPass1234!@"
}