### 장바구니 담기
POST {{commerce-api}}/api/v1/cart
Content-Type: application/json
X-Loopers-LoginId: {{loginId}}
X-Loopers-LoginPw: {{loginPw}}

{
  "optionId": 1,
  "quantity": 2
}

### 장바구니 조회
GET {{commerce-api}}/api/v1/cart
X-Loopers-LoginId: {{loginId}}
X-Loopers-LoginPw: {{loginPw}}

### 장바구니 수량 변경
PATCH {{commerce-api}}/api/v1/cart/1
Content-Type: application/json
X-Loopers-LoginId: {{loginId}}
X-Loopers-LoginPw: {{loginPw}}

{
  "quantity": 5
}

### 장바구니 삭제
DELETE {{commerce-api}}/api/v1/cart/1
X-Loopers-LoginId: {{loginId}}
X-Loopers-LoginPw: {{loginPw}}
