server:
  shutdown: graceful
  tomcat:
    threads:
      max: 200 # 최대 워커 스레드 수 (default : 200)
      min-spare: 10 # 최소 유지 스레드 수 (default : 10)
    connection-timeout: 1m # 연결 타임아웃 (ms) (default : 60000ms = 1m)
    max-connections: 8192 # 최대 동시 연결 수 (default : 8192)
    accept-count: 100 # 대기 큐 크기 (default : 100)
    keep-alive-timeout: 60s # 60s
  max-http-request-header-size: 8KB

spring:
  main:
    web-application-type: servlet
  application:
    name: commerce-api
  profiles:
    active: local
  config:
    import:
      - jpa.yml
      - redis.yml
      - logging.yml
      - monitoring.yml

pg-client:
  base-url: ${PG_BASE_URL}
  pg2-base-url: ${PG2_BASE_URL:${PG_BASE_URL}}
  callback-url: ${PG_CALLBACK_URL}
  connect-timeout: 1000
  read-timeout: 1000

resilience4j:
  circuitbreaker:
    configs:
      payment:
        sliding-window-type: TIME_BASED
        sliding-window-size: 60
        minimum-number-of-calls: 5
        failure-rate-threshold: 70
        slow-call-duration-threshold: 700ms
        slow-call-rate-threshold: 80
        wait-duration-in-open-state: 30s
        permitted-number-of-calls-in-half-open-state: 3
  bulkhead:
    instances:
      queue-order:
        maxConcurrentCalls: 20
        maxWaitDuration: 3s
  retry:
    configs:
      payment:
        max-attempts: 2
        wait-duration: 500ms
        ignore-exceptions:
          - io.github.resilience4j.circuitbreaker.CallNotPermittedException

queue:
  max-capacity: 10000
  token-ttl-seconds: 300
  batch-size: 10
  throughput-per-second: 100
  display-throughput-per-second: 80
  scheduler-interval: 100
  rate-limit:
    max-requests: 3
    ttl-seconds: 1

springdoc:
  use-fqn: true
  swagger-ui:
    path: /swagger-ui.html

---
spring:
  config:
    activate:
      on-profile: local, test

pg-client:
  nice-pg-base-url: http://localhost:8081
  toss-pg-base-url: http://localhost:8082
  callback-url: http://localhost:8080/api/v1/payments/callback

---
spring:
  config:
    activate:
      on-profile: test

queue:
  scheduler-interval: 999999999

---
spring:
  config:
    activate:
      on-profile: loadtest

management:
  endpoints:
    web:
      exposure:
        include: health,metrics
  endpoint:
    health:
      show-details: always

queue:
  scheduler-interval: 5000

pg-client:
  nice-pg-base-url: http://localhost:8081
  toss-pg-base-url: http://localhost:8082
  callback-url: http://localhost:8080/api/v1/payments/callback

---
spring:
  config:
    activate:
      on-profile: dev

---
spring:
  config:
    activate:
      on-profile: qa

---
spring:
  config:
    activate:
      on-profile: prd

springdoc:
  api-docs:
    enabled: false